### ISSUE TITLE
[Feature Request] We need a UI Interface for wdos main program

### ISSUE THREAD

**Issue by Dynesshely** [Catrol-org/Working-Desktop-OS#4]
Yeah, we need a program UI Interface for wdos main program.

**Comment by Dynesshely** [comment]
I did a Login in View and a Startup View

**Comment by Dynesshely** [comment]
# Startup View
![image](https://user-images.githubusercontent.com/50760269/158118530-17471649-eadc-4f5c-b9ac-6b5908e683c4.png)
# Login in View
![image](https://user-images.githubusercontent.com/50760269/158118561-87713d64-4254-4f93-a0a9-a011698227f4.png)
![image](https://user-images.githubusercontent.com/50760269/158118597-1bc17257-c32e-4a3d-99ed-e57f012b20e1.png)

@Ctkon What do you think of it?

**Comment by Ctkon** [comment]
I think it's quite smoot . That's it.👏

**Comment by Ctkon** [comment]
I think it's quite smooth . That's it.👏

**Comment by Dynesshely** [comment]
Do you have time to design a achitecture for account system ?
Thanks a lot @Ctkon 🤣

Wish for your every ✅AC

**Comment by Ctkon** [comment]
I think it's a good idea to make some groups to divide the users. You know what I mean.

**Comment by Dynesshely** [comment]
You're right.
We need many groups which include some users.
As we want, we need a super administrator goups and user -> "root" is the default user

**Comment by Ctkon** [comment]
Yes, you got it.
